' PlantUML Diagram
@startuml
title __PO Item Process__

' Swimlanes
|eShop UI|
|#AntiqueWhite|Buyer| 
|#AntiqueWhite|Purchasing-Escrow| 
|#AntiqueWhite|Seller| 
|eShop Admin UI|

|eShop Admin UI|
start
:Admin user marks **PO Item**
as 4 Ready for Goods Issue;

|Seller|
:Function **setPoItemReadyForGoodsIssue()**;

|Purchasing-Escrow|
:Function **setPoItemReadyForGoodsIssue()**;

#LightSkyBlue:Emits:
* **PurchaseItemReadyForGoodsIssueLog**.
(Po Item status 4 Ready for Goods Issue);

|eShop UI|
:User Sees: **PO Item** Status
4 Ready for Goods Issue;

|eShop Admin UI|
:Admin user marks **PO Item**
as 5 GoodsIssued;

|Seller|
:Function **setPoItemGoodsIssued()**;

|Purchasing-Escrow|
:Function **setPoItemGoodsIssued()**
Set Escrow Release date = Today + 30 days;

#LightSkyBlue:Emits:
* **PurchaseItemGoodsIssuedLog**.
(Po Item status 5 Goods Issued);

|eShop UI|
:User Sees: **PO Item** Status
5 Goods Issued;

split
  |eShop UI|
  :...parcel arrives...;
  :Buyer or delivery service can inform
  shop goods received (optional).;

  |Buyer|
  :Function: **setPoItemGoodsReceived()**
  If Po not goods issued, then revert.;

split again
  |eShop Admin UI|
  :...or 30 days pass...;
  
  |eShop Admin UI|
  :Admin user marks **PO Item**
  as 6 Goods Received.;

  |Seller|
  :Function: **setPoItemGoodsReceived()**
  If Po not goods issued or Po
  escrowReleaseDate not passed then revert.;

endsplit

|Purchasing-Escrow|
:Function: **setPoItemGoodsReceived()**, calls
Function: **requestPoItemEscrowRelease()**
Escrow funds released to seller, or request
denied. If released, flag item as paid.;

#LightSkyBlue:Emits:
* **PurchaseItemEscrowReleasedLog**
(Po Item status 7 Completed)
* **PurchaseItemEscrowFailedLog**
(Po Item status unchanged 6 Goods Received);

|eShop Admin UI|
:Admin user sees funds
released or request denied.;

|eShop UI|
:User Sees: **PO Item** complete,
no further dispute possible.;

stop

@enduml