using Nethereum.eShop.ApplicationCore.Entities.RulesEngine;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Nethereum.eShop.ApplicationCore.Interfaces
{
    /// <summary>
    /// 
    /// This interface will be the proxy of the persistence layer for reports generated by the rules engine.
    /// Even though it now inherits the IAsyncRepository interface, perhaps it should inherit an alternative
    /// interface that binds to a different persistence implementation, since reports should only be WORM 
    /// (written once, read many).  This makes reports unlike most other objects stored in the repositories.
    ///
    /// </summary>
    public interface IReportRepository : IAsyncRepository<RuleTreeReport>
    {
        Task<List<RuleTreeReport>> GetByRuleTreeIdAsync(int ruleTreeId);
    }
}
