using Nethereum.ABI.FunctionEncoding.Attributes;
/// <summary>
/// This class is not generated by code gen, it is manually added.
/// Use it to re-specify types in function messages, for example
/// when a Solidity field is bytes32 a byte array byte[] is produced
/// in C# code gen. However, we often know the bytes32 represents e.g. a 
/// string, so by redefining the type here, the conversion can happen
/// automatically.
/// Note that this means some code-generated methods need commented out
/// eg see BusinessPartnerStorageService.cs and method:
///   SetSystemDescriptionRequestAsync(byte[] systemId, byte[] systemDescription)
/// This method is commented out, because it uses non-redefined systemId of byte[].
/// </summary>
namespace Nethereum.Commerce.Contracts.BusinessPartnerStorage.ContractDefinition
{
    public partial class SetSystemDescriptionFunction
    {
        [Parameter("bytes32", "systemId", 1)]
        public new string SystemId { get; set; }
        [Parameter("bytes32", "systemDescription", 2)]
        public new string SystemDescription { get; set; }
    }

    public partial class SetWalletAddressFunction
    {
        [Parameter("bytes32", "systemId", 1)]
        public new string SystemId { get; set; }
    }
}
